
version: '3'

services:
  api:
    build: ./api
    command: rails s -p 3333 -b 0.0.0.0
    volumes:
      - ./api:/api
      - bundle:/bundle
    depends_on:
      - db
      - redis
      - sidekiq
    ports:
      - "3333:3333"
    tty: true
    environment:
      - BUNDLE_PATH=/bundle
      - RAILS_ENV=${RAILS_ENV}
  db:
    image: postgres:9.6.8-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
  redis:
    image: redis:6.0.4-alpine
  sidekiq:
    build: ./api
    volumes:
      - ./api:/api
    links:
      - db
      - redis
    command: bundle exec sidekiq
volumes:
  db-data:
  bundle:
