
version: '3'

services:
  api:
    build: ./api
    command: rails s -p 3333 -b 0.0.0.0
    volumes:
      - ./api:/api
      - bundle:/bundle
    depends_on:
      - db
      - redis
      - sidekiq
    ports:
      - "3333:3333"
    tty: true
    environment:
      - BUNDLE_PATH=/bundle
      - RAILS_ENV=${RAILS_ENV}
  db:
    image: postgres:9.6.8-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
  redis:
    image: redis:6.0.4-alpine
  proxy:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on: 
      - db
      - api
      - redis
    ports:
      - 33333:33333
      - 443:443
    tty: true
    environment:
      - SERVER_NAME=${SERVER_NAME}
  sidekiq:
    build: ./api
    volumes:
      - ./api:/api
    links:
      - db
      - redis
    command: bundle exec sidekiq
volumes:
  db-data:
  bundle:
