source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'audited', '~> 4.5'
gem 'cancancan'
gem 'carrierwave'
gem 'carrierwave-base64'
gem 'enumerize', github: 'brainspec/enumerize'
gem 'fcm'
gem 'kaminari'
gem 'knock'
gem 'pg'
gem 'puma', '~> 3.7'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 5.1.4'
gem 'redis'
gem 'elasticsearch-model', '~>7.1.1'
gem 'elasticsearch-rails', '~>7.1.1'

group :development, :test do
  gem 'bullet'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.7'
  gem 'rswag-specs'
end

group :development do
  gem 'better_errors'
  gem 'letter_opener'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'rubocop', require: false
  gem 'rubocop-rspec', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'shoulda-matchers', '~> 4.1.1'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
